#!/bin/sh

#cleanup
rm -rf obj_dir
rm -f F1_light.vcd

# run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace F1_light.sv --exe F1_light_tb.cpp

#build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f VF1_light.mk VF1_light

#run executable simulation file
obj_dir/VF1_light